//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTuneDesktop.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialsToSupplies = new HashSet<MaterialsToSupplies>();
            this.ServicesToOrders = new HashSet<ServicesToOrders>();
        }
    
        public int ID { get; set; }
        public int IDMaterialType { get; set; }
        public byte[] Photo { get; set; }
        public string Name { get; set; }
        public bool StockStatus { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual MaterialsType MaterialsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsToSupplies> MaterialsToSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesToOrders> ServicesToOrders { get; set; }
    }
}
