//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTuneDesktop.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsToSupplies
    {
        public int ID { get; set; }
        public int IDSupply { get; set; }
        public int IDMaterial { get; set; }
        public decimal TradePrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
