//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTuneDesktop.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesToOrders
    {
        public int ID { get; set; }
        public Nullable<int> IDMaterial { get; set; }
        public int IDService { get; set; }
        public int IDOrder { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual TypeOfServices TypeOfServices { get; set; }
    }
}
